# Prowler Helm Chart
apiVersion: v2
name: prowler
description: Prowler Helm Chart for Kubernetes - Cloud Security Tool
type: application
version: 0.0.1
appVersion: "latest"
home: https://prowler.com/
maintainers:
  - name: guilhermealegre
    email: guilhermealegre93@gmail.com
keywords:
  - security
  - prowler
  - cloud
  - kubernetes
  - aws
  - azure
  - gcp
  - kubernetes
  - github
  - cloud-security
  - cloud-security-tool
  - cloud-security-assessment
  - cloud-security-audit
  - cloud-security-compliance


